title: Anya Khanijow 
logo: https://media.licdn.com/dms/image/v2/D4E03AQH0Bknty_6jmQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1725035099758?e=1757548800&v=beta&t=tkr4QLX77MCZfMtruBsKcqszgEwHFQ3y2z9o0DWQKao
description: Turning messy data into meaningful stories
show_downloads: false 
remote_theme: mmistakes/minimal-mistakes 
minimal_mistakes_skin: "default"

